Document: dev
Title: Debian dev Manual
Author: <insert document author here>
Abstract: This manual describes what dev is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/dev/dev.sgml.gz

Format: postscript
Files: /usr/share/doc/dev/dev.ps.gz

Format: text
Files: /usr/share/doc/dev/dev.text.gz

Format: HTML
Index: /usr/share/doc/dev/html/index.html
Files: /usr/share/doc/dev/html/*.html
